# Site settings
title: open-eObs
email: openeobs@neovahealth.co.uk
description: > # this means to ignore newlines until "baseurl:"
  open-eObs - provides mobile apps for nursing observations & assessments,
  multidisciplinary escalation & handover and task & workload management.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jekyll.openeobs.net" # the base hostname & protocol for your site
fqdn: "jekyll.openeobs.net" # the FQDN for your site
# fqdn: "192.168.1.10:4000" # the FQDN for your site
twitter_username: openeobs
github_username:  neovahealth

# Build settings
markdown: kramdown

# Serving
detach:  false
port:    4000
host:    127.0.0.1