# Site settings
title: open-eObs from Neova Health
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  open-eObs - provides mobile apps for nursing observations & assessments,
  multidisciplinary escalation & handover and task & workload management.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jekyll.openeobs.net" # the base hostname & protocol for your site
twitter_username: openeobs
github_username:  neovahealth

# Build settings
markdown: kramdown

# Serving
detach:  false
port:    4000
host:    192.168.1.10